'use client';

import { formatDate, formatShortDate } from '@/lib/utils';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import {
  ArrowLeft,
  Download,
  Edit2,
  CheckCircle,
  Clock,
} from 'lucide-react';
import Link from 'next/link';

interface FinancialReport {
  id: string;
  name: string;
  type: string;
  financialYear: string;
  startDate: string;
  endDate: string;
  status: string;
  createdAt: string;
  data: any;
  generatedBy: {
    id: string;
    name: string;
    email: string;
  };
}

export default function ReportDetailPage() {
  const params = useParams();
  const reportId = params.id as string;
  const [report, setReport] = useState<FinancialReport | null>(null);
  const [loading, setLoading] = useState(true);
  const [updating, setUpdating] = useState(false);

  useEffect(() => {
    const fetchReport = async () => {
      try {
        setLoading(true);
        const response = await fetch(`/api/finance/reports/${reportId}`);
        if (!response.ok) throw new Error('Failed to fetch report');
        const data = await response.json();
        setReport(data);
      } catch (error) {
        console.error('Error fetching report:', error);
      } finally {
        setLoading(false);
      }
    };

    fetchReport();
  }, [reportId]);

  const handleApprove = async () => {
    try {
      setUpdating(true);
      const response = await fetch(`/api/finance/reports/${reportId}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status: 'APPROVED' }),
      });
      if (!response.ok) throw new Error('Failed to approve');
      const data = await response.json();
      setReport(data);
    } catch (error) {
      console.error('Error approving report:', error);
    } finally {
      setUpdating(false);
    }
  };


  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-GB', {
      style: 'currency',
      currency: 'GBP',
    }).format(amount);
  };

  if (loading) {
    return <div className="text-center py-12">Loading report...</div>;
  }

  if (!report) {
    return <div className="text-center py-12">Report not found</div>;
  }

  const isSOFA = report.type === 'SOFA';
  const data = report.data as any;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <Link href="/finance/reports">
            <Button variant="ghost" className="gap-2 mb-4">
              <ArrowLeft className="h-4 w-4" />
              Back to Reports
            </Button>
          </Link>
          <h1 className="text-3xl font-bold text-gray-900">{report.name}</h1>
          <p className="text-gray-500 mt-2">
            {formatDate(report.startDate)} to {formatDate(report.endDate)}
          </p>
        </div>
        <div className="space-y-2">
          <div className="flex gap-2">
            <Badge
              className={
                report.status === 'APPROVED'
                  ? 'bg-green-100 text-green-800'
                  : 'bg-yellow-100 text-yellow-800'
              }
            >
              {report.status === 'APPROVED' ? (
                <CheckCircle className="h-4 w-4 mr-1" />
              ) : (
                <Clock className="h-4 w-4 mr-1" />
              )}
              {report.status}
            </Badge>
          </div>
          {report.status === 'DRAFT' && (
            <Button
              onClick={handleApprove}
              disabled={updating}
              className="w-full"
            >
              {updating ? 'Approving...' : 'Approve Report'}
            </Button>
          )}
        </div>
      </div>

      {/* Report Info Card */}
      <Card className="p-6 bg-gray-50">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div>
            <p className="text-sm text-gray-600">Financial Year</p>
            <p className="font-semibold text-gray-900">{report.financialYear}</p>
          </div>
          <div>
            <p className="text-sm text-gray-600">Report Type</p>
            <p className="font-semibold text-gray-900">
              {isSOFA ? 'SOFA' : 'Balance Sheet'}
            </p>
          </div>
          <div>
            <p className="text-sm text-gray-600">Generated By</p>
            <p className="font-semibold text-gray-900">
              {report.generatedBy.name}
            </p>
          </div>
          <div>
            <p className="text-sm text-gray-600">Generated At</p>
            <p className="font-semibold text-gray-900">
              {formatDate(report.createdAt)}
            </p>
          </div>
        </div>
      </Card>

      {/* SOFA Report */}
      {isSOFA && (
        <div className="space-y-6">
          {/* Income Section */}
          <Card className="p-6">
            <h2 className="text-xl font-bold text-gray-900 mb-4">Income</h2>
            <div className="space-y-4">
              <div className="grid grid-cols-3 gap-4">
                <div className="p-4 bg-blue-50 rounded-lg">
                  <p className="text-sm text-gray-600">Donations</p>
                  <p className="text-lg font-bold text-blue-900">
                    {formatCurrency(data.income?.donations?.total || 0)}
                  </p>
                  <p className="text-xs text-gray-500 mt-1">
                    Unrestricted:{' '}
                    {formatCurrency(data.income?.donations?.unrestricted || 0)}
                  </p>
                </div>
                <div className="p-4 bg-green-50 rounded-lg">
                  <p className="text-sm text-gray-600">Grants</p>
                  <p className="text-lg font-bold text-green-900">
                    {formatCurrency(data.income?.grants?.total || 0)}
                  </p>
                  <p className="text-xs text-gray-500 mt-1">
                    Restricted:{' '}
                    {formatCurrency(data.income?.grants?.restricted || 0)}
                  </p>
                </div>
                <div className="p-4 bg-purple-50 rounded-lg">
                  <p className="text-sm text-gray-600">Memberships</p>
                  <p className="text-lg font-bold text-purple-900">
                    {formatCurrency(data.income?.memberships?.total || 0)}
                  </p>
                </div>
              </div>
              <div className="border-t pt-4">
                <div className="flex justify-between items-center">
                  <p className="font-semibold text-gray-900">Total Income</p>
                  <p className="text-2xl font-bold text-green-600">
                    {formatCurrency(data.income?.totalIncome || 0)}
                  </p>
                </div>
              </div>
            </div>
          </Card>

          {/* Expenditure Section */}
          <Card className="p-6">
            <h2 className="text-xl font-bold text-gray-900 mb-4">Expenditure</h2>
            <div className="space-y-3">
              <div className="grid grid-cols-3 gap-4">
                <div className="p-4 bg-orange-50 rounded-lg">
                  <p className="text-sm text-gray-600">Charitable Activities</p>
                  <p className="text-lg font-bold text-orange-900">
                    {formatCurrency(data.expenditure?.charitable?.total || 0)}
                  </p>
                </div>
                <div className="p-4 bg-yellow-50 rounded-lg">
                  <p className="text-sm text-gray-600">Support Costs</p>
                  <p className="text-lg font-bold text-yellow-900">
                    {formatCurrency(data.expenditure?.support?.total || 0)}
                  </p>
                </div>
                <div className="p-4 bg-red-50 rounded-lg">
                  <p className="text-sm text-gray-600">Governance</p>
                  <p className="text-lg font-bold text-red-900">
                    {formatCurrency(data.expenditure?.governance?.total || 0)}
                  </p>
                </div>
              </div>
              <div className="border-t pt-4">
                <div className="flex justify-between items-center">
                  <p className="font-semibold text-gray-900">Total Expenditure</p>
                  <p className="text-2xl font-bold text-red-600">
                    {formatCurrency(data.expenditure?.totalExpenditure || 0)}
                  </p>
                </div>
              </div>
            </div>
          </Card>

          {/* Net Movement Section */}
          <Card className="p-6 bg-gradient-to-r from-green-50 to-blue-50">
            <h2 className="text-xl font-bold text-gray-900 mb-4">Net Movement</h2>
            <div className="grid grid-cols-3 gap-4">
              <div>
                <p className="text-sm text-gray-600">Unrestricted Funds</p>
                <p className="text-2xl font-bold text-gray-900">
                  {formatCurrency(data.netMovement?.unrestricted || 0)}
                </p>
              </div>
              <div>
                <p className="text-sm text-gray-600">Restricted Funds</p>
                <p className="text-2xl font-bold text-gray-900">
                  {formatCurrency(data.netMovement?.restricted || 0)}
                </p>
              </div>
              <div className="border-l pl-4">
                <p className="text-sm text-gray-600">Total Net Movement</p>
                <p className="text-2xl font-bold text-green-600">
                  {formatCurrency(data.netMovement?.total || 0)}
                </p>
              </div>
            </div>
          </Card>
        </div>
      )}

      {/* Balance Sheet Report */}
      {!isSOFA && (
        <div className="space-y-6">
          {/* Assets Section */}
          <Card className="p-6">
            <h2 className="text-xl font-bold text-gray-900 mb-4">Assets</h2>
            <div className="space-y-4">
              <div>
                <p className="text-sm font-semibold text-gray-600 mb-2">
                  Fixed Assets
                </p>
                <div className="ml-4 space-y-2 text-sm">
                  <div className="flex justify-between">
                    <span>Tangible Fixed Assets</span>
                    <span>{formatCurrency(data.fixedAssets?.tangible || 0)}</span>
                  </div>
                  <div className="flex justify-between">
                    <span>Intangible Fixed Assets</span>
                    <span>{formatCurrency(data.fixedAssets?.intangible || 0)}</span>
                  </div>
                  <div className="flex justify-between font-semibold border-t pt-2">
                    <span>Total Fixed Assets</span>
                    <span>
                      {formatCurrency(data.fixedAssets?.totalFixedAssets || 0)}
                    </span>
                  </div>
                </div>
              </div>
              <div className="border-t pt-4">
                <p className="text-sm font-semibold text-gray-600 mb-2">
                  Current Assets
                </p>
                <div className="ml-4 space-y-2 text-sm">
                  <div className="flex justify-between">
                    <span>Cash</span>
                    <span>{formatCurrency(data.currentAssets?.cash || 0)}</span>
                  </div>
                  <div className="flex justify-between">
                    <span>Receivables</span>
                    <span>
                      {formatCurrency(data.currentAssets?.receivables || 0)}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span>Inventory</span>
                    <span>
                      {formatCurrency(data.currentAssets?.inventory || 0)}
                    </span>
                  </div>
                  <div className="flex justify-between font-semibold border-t pt-2">
                    <span>Total Current Assets</span>
                    <span>
                      {formatCurrency(
                        data.currentAssets?.totalCurrentAssets || 0
                      )}
                    </span>
                  </div>
                </div>
              </div>
              <div className="border-t pt-4 bg-blue-50 p-4 rounded">
                <div className="flex justify-between font-bold text-gray-900">
                  <span>Total Assets</span>
                  <span className="text-lg">
                    {formatCurrency(data.totalAssets || 0)}
                  </span>
                </div>
              </div>
            </div>
          </Card>

          {/* Liabilities and Funds Section */}
          <Card className="p-6">
            <h2 className="text-xl font-bold text-gray-900 mb-4">
              Liabilities and Funds
            </h2>
            <div className="space-y-4">
              <div>
                <p className="text-sm font-semibold text-gray-600 mb-2">
                  Current Liabilities
                </p>
                <div className="ml-4 space-y-2 text-sm">
                  <div className="flex justify-between">
                    <span>Payables</span>
                    <span>
                      {formatCurrency(data.currentLiabilities?.payables || 0)}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span>Accruals</span>
                    <span>
                      {formatCurrency(data.currentLiabilities?.accruals || 0)}
                    </span>
                  </div>
                  <div className="flex justify-between font-semibold border-t pt-2">
                    <span>Total Current Liabilities</span>
                    <span>
                      {formatCurrency(
                        data.currentLiabilities?.totalCurrentLiabilities || 0
                      )}
                    </span>
                  </div>
                </div>
              </div>
              <div className="border-t pt-4">
                <p className="text-sm font-semibold text-gray-600 mb-2">Funds</p>
                <div className="ml-4 space-y-2 text-sm">
                  <div className="flex justify-between">
                    <span>Unrestricted Funds</span>
                    <span>
                      {formatCurrency(data.funds?.unrestrictedFunds || 0)}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span>Restricted Funds</span>
                    <span>
                      {formatCurrency(data.funds?.restrictedFunds || 0)}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span>Endowment Funds</span>
                    <span>
                      {formatCurrency(data.funds?.endowmentFunds || 0)}
                    </span>
                  </div>
                  <div className="flex justify-between font-semibold border-t pt-2">
                    <span>Total Funds</span>
                    <span>{formatCurrency(data.funds?.totalFunds || 0)}</span>
                  </div>
                </div>
              </div>
            </div>
          </Card>
        </div>
      )}
    </div>
  );
}
