import { NextRequest, NextResponse } from "next/server";
import { getSession } from "@/lib/session";
import { prisma } from "@/lib/prisma";

interface ExportSection {
  title: string;
  data: Record<string, unknown>;
}

function formatValue(value: unknown, indent: number = 0): string {
  const prefix = "  ".repeat(indent);
  if (value === null || value === undefined) return `${prefix}-`;
  if (typeof value === "number") {
    if (Number.isInteger(value)) return `${prefix}${value.toLocaleString()}`;
    return `${prefix}£${value.toLocaleString("en-GB", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  }
  if (typeof value === "string") return `${prefix}${value}`;
  if (Array.isArray(value)) {
    return value
      .map((item) => {
        if (typeof item === "object" && item !== null) {
          const entries = Object.entries(item as Record<string, unknown>)
            .map(([k, v]) => `${k}: ${formatValue(v)}`)
            .join(", ");
          return `${prefix}  - ${entries}`;
        }
        return `${prefix}  - ${String(item)}`;
      })
      .join("\n");
  }
  if (typeof value === "object") {
    return Object.entries(value as Record<string, unknown>)
      .map(([k, v]) => `${prefix}  ${k}: ${formatValue(v)}`)
      .join("\n");
  }
  return `${prefix}${String(value)}`;
}

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = await getSession();
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { id } = await params;

  const report = await prisma.boardReport.findUnique({
    where: { id },
    include: {
      generatedBy: { select: { name: true } },
    },
  });

  if (!report) {
    return NextResponse.json({ error: "Report not found" }, { status: 404 });
  }

  const data = report.data as { summary?: Record<string, unknown>; sections?: ExportSection[] };

  let text = `${"=".repeat(60)}\n`;
  text += `${report.title}\n`;
  text += `${"=".repeat(60)}\n\n`;
  text += `Period: ${report.period}\n`;
  text += `Date Range: ${report.startDate.toLocaleDateString()} - ${report.endDate.toLocaleDateString()}\n`;
  text += `Status: ${report.status}\n`;
  text += `Generated by: ${report.generatedBy.name}\n`;
  text += `Generated at: ${report.createdAt.toLocaleString()}\n\n`;

  if (data.summary) {
    text += `${"─".repeat(40)}\nEXECUTIVE SUMMARY\n${"─".repeat(40)}\n\n`;
    for (const [key, value] of Object.entries(data.summary)) {
      const label = key.replace(/([A-Z])/g, " $1").replace(/^./, (s) => s.toUpperCase());
      text += `${label}: ${formatValue(value)}\n`;
    }
    text += "\n";
  }

  if (data.sections) {
    for (const section of data.sections) {
      text += `${"─".repeat(40)}\n${section.title.toUpperCase()}\n${"─".repeat(40)}\n\n`;
      for (const [key, value] of Object.entries(section.data)) {
        const label = key.replace(/([A-Z])/g, " $1").replace(/^./, (s) => s.toUpperCase());
        text += `${label}:\n${formatValue(value, 1)}\n\n`;
      }
    }
  }

  if (report.narrative) {
    text += `${"─".repeat(40)}\nNARRATIVE / NOTES\n${"─".repeat(40)}\n\n`;
    text += `${report.narrative}\n\n`;
  }

  text += `${"=".repeat(60)}\nEnd of Report\n${"=".repeat(60)}\n`;

  const { searchParams } = new URL(req.url);
  const format = searchParams.get("format") ?? "text";

  if (format === "csv") {
    // Export summary as CSV
    let csv = "Metric,Value\n";
    if (data.summary) {
      for (const [key, value] of Object.entries(data.summary)) {
        const label = key.replace(/([A-Z])/g, " $1").trim();
        csv += `"${label}","${String(value)}"\n`;
      }
    }
    return new NextResponse(csv, {
      headers: {
        "Content-Type": "text/csv",
        "Content-Disposition": `attachment; filename="${report.title.replace(/[^a-zA-Z0-9]/g, "_")}.csv"`,
      },
    });
  }

  return new NextResponse(text, {
    headers: {
      "Content-Type": "text/plain",
      "Content-Disposition": `attachment; filename="${report.title.replace(/[^a-zA-Z0-9]/g, "_")}.txt"`,
    },
  });
}
